In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [ ]:
# -------------------
# 1. 데이터 불러오기
# -------------------
file_path = "../../data/RST-CLIMATESHELTER/RST-CLIMATESHELTER.csv"
df = pd.read_csv(file_path)

# -------------------
# 2. '구이름' 정제
# -------------------
def standardize_gu(name: str) -> str:
    """구 이름 표준화 함수"""
    if pd.isna(name):
        return name
    name = str(name).strip()  # 앞뒤 공백 제거
    name = name.replace("\n", "").replace("\r", "")  # 줄바꿈 제거
    
    mapping = {
        "강남 구": "강남구",
        "용산 구": "용산구",
        "서 초구": "서초구",
        # 필요시 다른 오타/변형 추가
    }
    return mapping.get(name, name)

df["구이름"] = df["구이름"].apply(standardize_gu)

# -------------------
# 3. 자치구별 쉼터 수 집계
# -------------------
gu_counts = df.groupby("구이름").size().reset_index(name="climateshelter_count")

# -------------------
# 4. MinMax Scaling (0~100점)
# -------------------
scaler = MinMaxScaler(feature_range=(0, 100))
gu_counts["climateshelter_score"] = scaler.fit_transform(
    gu_counts[["climateshelter_count"]]
)

# -------------------
# 5. 평균 점수 (여기서는 동일 → 그대로 복사)
# -------------------
gu_counts["climateshelter_mean_score"] = gu_counts["climateshelter_score"]

# -------------------
# 6. 저장
# -------------------
output_path = "../../result/RST/RST-CLIMATESHELTER_result.csv"
gu_counts.to_csv(output_path, index=False, encoding="utf-8-sig")

print("처리 완료:", output_path)
gu_counts.head()

처리 완료: ../../result/RST/RST_CLIMATESHELTER_result.csv

   구이름  climateshelter_count  climateshelter_score  climateshelter_mean_score
0  강남구                    49            100.000000                 100.000000
1  강동구                    15             20.930233                  20.930233
2  강북구                    16             23.255814                  23.255814
3  강서구                    34             65.116279                  65.116279
4  관악구                    16             23.255814                  23.255814